In [52]:
import pandas as pd
from matplotlib import pyplot
import numpy as np

In [53]:
df = pd.read_csv("Sales_Transactions_Dataset_Weekly.csv")

In [54]:
df.sample(5)

,Product_Code,W0,W1,W2,W3,W4,W5,W6,W7,W8,...,Normalized 42,Normalized 43,Normalized 44,Normalized 45,Normalized 46,Normalized 47,Normalized 48,Normalized 49,Normalized 50,Normalized 51
185,P186,36,34,37,36,41,33,51,43,21,...,0.55,0.71,0.48,0.42,0.23,0.48,0.48,0.23,0.06,0.00
278,P279,0,0,0,0,0,0,0,0,0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
148,P149,11,9,9,6,13,8,11,14,14,...,0.20,0.50,0.30,0.70,0.40,0.80,0.30,0.30,0.30,0.10
297,P298,5,7,4,1,4,3,5,3,7,...,0.00,0.11,0.67,0.44,0.44,0.11,0.56,0.67,0.56,0.89
642,P646,0,0,0,0,0,0,0,0,0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1.00,0.00,0.00

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 811 entries, 0 to 810
Columns: 107 entries, Product_Code to Normalized 51
dtypes: float64(52), int64(54), object(1)
memory usage: 678.1+ KB

In [56]:
df.describe()

,W0,W1,W2,W3,W4,W5,W6,W7,W8,W9,...,Normalized 42,Normalized 43,Normalized 44,Normalized 45,Normalized 46,Normalized 47,Normalized 48,Normalized 49,Normalized 50,Normalized 51
count,811.000000,811.000000,811.000000,811.000000,811.000000,811.000000,811.000000,811.000000,811.000000,811.000000,...,811.000000,811.000000,811.000000,811.000000,811.000000,811.000000,811.00000,811.000000,811.000000,811.000000
mean,8.902589,9.129470,9.389642,9.717633,9.574599,9.466091,9.720099,9.585697,9.784217,9.681874,...,0.299149,0.287571,0.304846,0.316017,0.334760,0.314636,0.33815,0.358903,0.373009,0.427941
std,12.067163,12.564766,13.045073,13.553294,13.095765,12.823195,13.347375,13.049138,13.550237,13.137916,...,0.266993,0.256630,0.263396,0.262226,0.275203,0.266029,0.27569,0.286665,0.295197,0.342360
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.020000,0.085000,0.000000,0.10500,0.100000,0.110000,0.090000
50%,3.000000,3.000000,3.000000,4.000000,4.000000,3.000000,4.000000,4.000000,4.000000,4.000000,...,0.280000,0.270000,0.300000,0.310000,0.330000,0.310000,0.33000,0.330000,0.350000,0.430000
75%,12.000000,12.000000,12.000000,13.000000,13.000000,12.500000,13.000000,12.500000,13.000000,13.000000,...,0.490000,0.450000,0.500000,0.500000,0.500000,0.500000,0.50000,0.550000,0.560000,0.670000
max,54.000000,53.000000,56.000000,59.000000,61.000000,52.000000,56.000000,62.000000,63.000000,52.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000

In [57]:
new = df.drop(df.columns[df.columns.str.contains('^W')], axis=1)

In [58]:
new.sample(1)

,Product_Code,MIN,MAX,Normalized 0,Normalized 1,Normalized 2,Normalized 3,Normalized 4,Normalized 5,Normalized 6,...,Normalized 42,Normalized 43,Normalized 44,Normalized 45,Normalized 46,Normalized 47,Normalized 48,Normalized 49,Normalized 50,Normalized 51
234,P235,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0

In [59]:
new = new.drop('MIN', axis=1)

In [60]:
new = new.drop('MAX' , axis=1)

In [61]:
new.sample(1)

,Product_Code,Normalized 0,Normalized 1,Normalized 2,Normalized 3,Normalized 4,Normalized 5,Normalized 6,Normalized 7,Normalized 8,...,Normalized 42,Normalized 43,Normalized 44,Normalized 45,Normalized 46,Normalized 47,Normalized 48,Normalized 49,Normalized 50,Normalized 51
401,P404,0.53,0.33,0.27,0.4,0.53,0.2,0.47,0.67,0.33,...,0.13,0.13,0.27,0.2,0.27,0.6,0.33,0.73,0.73,0.67

In [62]:
new.describe()

,Normalized 0,Normalized 1,Normalized 2,Normalized 3,Normalized 4,Normalized 5,Normalized 6,Normalized 7,Normalized 8,Normalized 9,...,Normalized 42,Normalized 43,Normalized 44,Normalized 45,Normalized 46,Normalized 47,Normalized 48,Normalized 49,Normalized 50,Normalized 51
count,811.000000,811.000000,811.000000,811.000000,811.000000,811.000000,811.000000,811.000000,811.00000,811.000000,...,811.000000,811.000000,811.000000,811.000000,811.000000,811.000000,811.00000,811.000000,811.000000,811.000000
mean,0.289396,0.299100,0.306732,0.319852,0.326905,0.319420,0.332848,0.326572,0.32434,0.326843,...,0.299149,0.287571,0.304846,0.316017,0.334760,0.314636,0.33815,0.358903,0.373009,0.427941
std,0.266307,0.281343,0.284234,0.296498,0.297291,0.292765,0.301855,0.298986,0.29320,0.292093,...,0.266993,0.256630,0.263396,0.262226,0.275203,0.266029,0.27569,0.286665,0.295197,0.342360
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,...,0.000000,0.000000,0.000000,0.020000,0.085000,0.000000,0.10500,0.100000,0.110000,0.090000
50%,0.250000,0.280000,0.290000,0.290000,0.310000,0.300000,0.310000,0.330000,0.32000,0.330000,...,0.280000,0.270000,0.300000,0.310000,0.330000,0.310000,0.33000,0.330000,0.350000,0.430000
75%,0.500000,0.500000,0.500000,0.535000,0.550000,0.520000,0.530000,0.540000,0.53500,0.530000,...,0.490000,0.450000,0.500000,0.500000,0.500000,0.500000,0.50000,0.550000,0.560000,0.670000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000

In [63]:
new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 811 entries, 0 to 810
Data columns (total 53 columns):
Product_Code     811 non-null object
Normalized 0     811 non-null float64
Normalized 1     811 non-null float64
Normalized 2     811 non-null float64
Normalized 3     811 non-null float64
Normalized 4     811 non-null float64
Normalized 5     811 non-null float64
Normalized 6     811 non-null float64
Normalized 7     811 non-null float64
Normalized 8     811 non-null float64
Normalized 9     811 non-null float64
Normalized 10    811 non-null float64
Normalized 11    811 non-null float64
Normalized 12    811 non-null float64
Normalized 13    811 non-null float64
Normalized 14    811 non-null float64
Normalized 15    811 non-null float64
Normalized 16    811 non-null float64
Normalized 17    811 non-null float64
Normalized 18    811 non-null float64
Normalized 19    811 non-null float64
Normalized 20    811 non-null float64
Normalized 21    811 non-null float64
Normalized 22    811 non-null float64
Normalized 23    811 non-null float64
Normalized 24    811 non-null float64
Normalized 25    811 non-null float64
Normalized 26    811 non-null float64
Normalized 27    811 non-null float64
Normalized 28    811 non-null float64
Normalized 29    811 non-null float64
Normalized 30    811 non-null float64
Normalized 31    811 non-null float64
Normalized 32    811 non-null float64
Normalized 33    811 non-null float64
Normalized 34    811 non-null float64
Normalized 35    811 non-null float64
Normalized 36    811 non-null float64
Normalized 37    811 non-null float64
Normalized 38    811 non-null float64
Normalized 39    811 non-null float64
Normalized 40    811 non-null float64
Normalized 41    811 non-null float64
Normalized 42    811 non-null float64
Normalized 43    811 non-null float64
Normalized 44    811 non-null float64
Normalized 45    811 non-null float64
Normalized 46    811 non-null float64
Normalized 47    811 non-null float64
Normalized 48    811 non-null float64
Normalized 49    811 non-null float64
Normalized 50    811 non-null float64
Normalized 51    811 non-null float64
dtypes: float64(52), object(1)
memory usage: 335.9+ KB

In [64]:
df = new.set_index('Product_Code')

In [65]:
df

,Normalized 0,Normalized 1,Normalized 2,Normalized 3,Normalized 4,Normalized 5,Normalized 6,Normalized 7,Normalized 8,Normalized 9,...,Normalized 42,Normalized 43,Normalized 44,Normalized 45,Normalized 46,Normalized 47,Normalized 48,Normalized 49,Normalized 50,Normalized 51
Product_Code,,,,,,,,,,,,,,,,,,,,,
P1,0.44,0.50,0.39,0.28,0.56,0.50,0.61,1.00,0.17,0.61,...,0.06,0.22,0.28,0.39,0.50,0.00,0.22,0.17,0.11,0.39
P2,0.70,0.60,0.30,0.20,0.70,0.10,0.60,0.30,0.30,0.30,...,0.20,0.40,0.50,0.10,0.10,0.40,0.50,0.10,0.60,0.00
P3,0.36,0.73,0.45,0.55,0.64,0.45,0.36,0.91,0.82,0.27,...,0.27,1.00,0.18,0.18,0.36,0.45,1.00,0.45,0.45,0.36
P4,0.59,0.35,0.65,0.18,0.41,0.24,0.41,0.65,0.65,0.53,...,0.41,0.47,0.06,0.12,0.24,0.35,0.71,0.35,0.29,0.35
P5,0.33,0.13,0.67,0.53,0.20,0.27,0.40,0.73,0.40,0.40,...,0.27,0.53,0.27,0.60,0.20,0.20,0.13,0.53,0.33,0.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
P815,0.00,0.00,0.33,0.00,0.00,0.67,0.33,0.00,0.00,0.33,...,0.00,0.33,0.33,0.00,0.00,0.33,0.00,0.00,0.67,0.00
P816,0.00,0.14,0.00,0.00,0.14,0.29,0.29,0.86,0.00,0.14,...,0.43,0.43,0.57,0.29,0.57,0.71,0.71,0.71,0.86,0.71
P817,0.25,0.00,0.00,0.00,0.25,0.25,0.50,0.25,0.25,0.00,...,0.50,0.00,0.00,0.50,0.50,0.00,0.00,0.00,1.00,0.75
P818,0.00,0.00,0.00,0.50,0.00,0.00,0.00,0.00,0.50,0.00,...,0.00,0.00,0.00,0.50,0.50,0.00,0.00,0.00,1.00,0.00
P819,0.00,0.33,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.33

In [66]:
data = df.T
data

Product_Code,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10,...,P810,P811,P812,P813,P814,P815,P816,P817,P818,P819
Normalized 0,0.44,0.7,0.36,0.59,0.33,0.27,0.4,0.42,0.73,0.54,...,0.00,0.56,0.50,0.13,0.25,0.00,0.00,0.25,0.0,0.00
Normalized 1,0.50,0.6,0.73,0.35,0.13,0.27,0.8,0.25,0.40,0.42,...,0.00,0.11,0.33,0.13,0.13,0.00,0.14,0.00,0.0,0.33
Normalized 2,0.39,0.3,0.45,0.65,0.67,0.18,0.3,0.58,0.47,0.42,...,0.33,0.33,0.00,0.13,0.13,0.33,0.00,0.00,0.0,0.00
Normalized 3,0.28,0.2,0.55,0.18,0.53,0.64,0.7,0.50,0.27,0.83,...,0.00,0.56,0.00,0.38,0.38,0.00,0.00,0.00,0.5,0.00
Normalized 4,0.56,0.7,0.64,0.41,0.20,0.55,0.8,0.25,0.53,0.46,...,0.00,0.44,0.33,0.25,0.00,0.00,0.14,0.25,0.0,0.00
Normalized 5,0.50,0.1,0.45,0.24,0.27,0.27,0.7,0.42,0.80,0.29,...,0.00,0.44,0.17,0.25,0.25,0.67,0.29,0.25,0.0,0.00
Normalized 6,0.61,0.6,0.36,0.41,0.40,0.73,0.2,0.33,0.60,0.71,...,0.00,0.44,0.00,0.63,0.44,0.33,0.29,0.50,0.0,0.00
Normalized 7,1.00,0.3,0.91,0.65,0.73,0.55,0.3,0.17,0.27,0.46,...,0.00,0.22,0.33,0.63,0.50,0.00,0.86,0.25,0.0,0.00
Normalized 8,0.17,0.3,0.82,0.65,0.40,0.55,1.0,0.58,0.67,0.63,...,0.00,0.22,0.33,0.13,0.19,0.00,0.00,0.25,0.5,0.00
Normalized 9,0.61,0.3,0.27,0.53,0.40,0.27,0.3,0.58,0.60,0.46,...,0.00,0.33,0.33,0.38,0.13,0.33,0.14,0.00,0.0,0.00
Normalized 10,0.44,0.2,1.00,0.35,0.53,0.09,0.5,0.42,0.80,0.92,...,0.00,0.33,0.17,0.25,0.38,0.00,0.00,0.00,0.0,0.00
Normalized 11,0.61,0.2,0.55,0.12,1.00,0.09,0.2,0.42,0.80,0.54,...,0.00,0.33,1.00,0.13,0.56,0.00,0.29,0.25,0.0,0.00
Normalized 12,0.72,0.6,0.09,0.18,0.33,0.45,0.3,1.00,0.87,0.58,...,0.33,0.56,0.50,0.00,0.31,0.33,0.29,0.00,0.0,0.00
Normalized 13,0.33,0.2,0.36,0.12,0.07,0.36,0.4,0.50,0.47,0.42,...,0.00,0.33,0.33,0.63,0.25,0.00,0.00,0.00,0.0,0.00
Normalized 14,0.33,0.0,0.82,0.76,0.67,0.27,0.5,0.17,0.40,0.25,...,0.00,0.44,0.33,0.25,0.31,0.33,0.71,0.00,0.0,0.00
Normalized 15,0.33,0.6,0.45,0.29,0.33,0.45,0.3,0.67,0.40,0.42,...,0.00,0.44,0.17,0.00,0.19,0.33,0.14,0.00,0.0,0.00
Normalized 16,0.61,0.2,0.36,0.53,0.47,0.27,0.7,0.58,0.67,0.54,...,0.33,0.33,0.17,0.38,0.25,1.00,0.14,0.00,0.0,0.00
Normalized 17,0.33,0.7,0.73,0.41,0.80,0.45,1.0,0.33,0.33,0.58,...,0.00,0.22,0.00,0.25,0.19,0.00,0.14,0.00,0.0,0.00
Normalized 18,0.00,0.7,0.64,0.76,0.20,0.91,0.0,0.83,0.47,0.46,...,0.00,0.44,0.17,0.63,0.38,0.00,0.29,0.00,0.0,1.00
Normalized 19,0.50,0.9,0.36,0.12,0.67,0.73,0.3,0.50,1.00,1.00,...,0.00,0.22,0.17,0.00,0.31,0.00,0.43,0.00,0.5,0.00
Normalized 20,0.11,0.4,0.36,0.24,0.53,0.36,0.7,0.75,1.00,0.29,...,0.00,0.22,0.17,0.38,0.31,0.00,0.14,0.25,0.0,0.00
Normalized 21,0.44,0.7,0.91,0.29,0.20,0.82,0.5,0.67,0.93,0.58,...,0.00,0.67,0.17,0.25,0.19,0.00,0.00,0.00,0.0,0.00
Normalized 22,0.22,0.2,0.73,0.53,0.47,0.64,0.1,0.17,0.47,0.58,...,0.00,0.22,0.33,0.50,0.19,0.00,0.29,0.00,0.5,0.67
Normalized 23,0.50,0.4,0.45,0.29,0.40,0.45,0.5,0.67,0.87,0.29,...,0.00,0.78,0.33,1.00,0.75,0.33,0.14,0.00,0.0,0.00
Normalized 24,0.11,0.5,0.64,0.41,0.33,0.36,0.7,0.67,0.73,0.67,...,0.00,0.22,0.33,0.63,0.56,0.00,1.00,0.25,1.0,0.00
Normalized 25,0.33,0.3,0.45,0.24,0.60,0.18,0.5,0.75,0.47,0.75,...,0.00,1.00,0.33,0.63,0.44,0.00,0.43,0.00,0.5,0.00
Normalized 26,0.22,0.5,1.00,0.47,0.33,0.09,0.2,0.00,0.07,0.13,...,0.33,0.67,0.00,0.13,0.19,0.00,0.43,0.00,0.5,0.33
Normalized 27,0.39,0.8,0.18,0.47,0.40,0.27,0.4,0.58,0.27,0.25,...,0.67,0.22,0.33,0.00,0.38,0.00,0.43,0.25,0.0,0.00
Normalized 28,0.11,0.5,0.00,0.00,0.67,0.18,0.3,0.75,0.27,0.25,...,1.00,0.44,0.50,0.38,0.31,0.67,0.29,0.00,0.5,0.00
Normalized 29,0.44,0.5,0.91,0.24,0.00,0.36,0.1,0.50,0.47,0.08,...,0.00,0.33,0.17,0.00,0.19,0.00,0.29,0.00,0.5,0.00
Normalized 30,0.22,0.3,0.73,0.29,0.13,0.00,0.3,0.50,0.00,0.21,...,0.00,0.33,0.00,0.13,0.44,0.00,0.43,0.00,0.0,0.00
Normalized 31,0.39,0.1,0.55,0.00,0.00,0.27,0.2,0.58,0.67,0.83,...,0.00,0.44,0.17,0.13,0.25,0.00,0.14,0.00,0.5,0.00
Normalized 32,0.50,0.3,0.36,0.18,0.13,0.18,0.2,0.42,0.40,0.58,...,0.33,0.56,0.33,0.13,0.19,0.00,0.14,0.00,0.5,0.33
Normalized 33,0.17,0.2,0.45,0.59,0.13,1.00,0.4,0.50,0.27,0.13,...,0.00,0.00,0.17,0.50,0.38,0.00,0.57,0.25,0.5,0.00
Normalized 34,0.11,0.3,0.36,0.18,0.40,0.18,0.2,0.42,0.40,0.29,...,0.00,0.44,0.33,0.13,0.19,0.00,0.71,0.00,0.0,0.00
Normalized 35,0.61,1.0,0.55,1.00,0.27,0.09,0.6,0.50,0.33,0.00,...,0.33,0.11,0.00,0.63,0.50,0.00,0.57,0.00,0.0,1.00
Normalized 36,0.39,0.5,0.27,0.35,0.07,0.36,0.4,1.00,0.27,0.58,...,1.00,0.56,0.17,0.13,0.06,0.00,0.43,0.00,0.0,0.33
Normalized 37,0.33,0.2,0.82,0.24,0.33,0.36,0.5,0.25,0.40,0.54,...,0.00,0.33,0.00,0.38,0.13,0.00,0.29,0.00,0.0,0.33
Normalized 38,0.50,0.7,0.82,0.35,0.33,0.27,0.1,0.33,0.80,0.25,...,0.00,0.44,0.33,0.13,0.19,0.33,0.57,0.00,0.0,0.33
Normalized 39,0.78,0.3,0.55,0.35,0.13,0.18,0.3,0.42,0.33,0.38,...,0.33,0.44,0.33,0.25,0.25,0.67,0.86,0.00,0.0,0.00
Normalized 40,0.22,0.2,0.00,0.59,0.13,0.45,0.5,0.00,0.40,0.17,...,0.00,0.11,0.33,0.50,0.19,0.33,0.86,0.00,0.0,0.33
Normalized 41,0.44,0.5,0.18,0.24,0.33,0.36,0.8,0.50,0.33,0.33,...,0.00,0.22,0.17,0.13,0.50,0.00,1.00,0.25,0.0,0.00
Normalized 42,0.06,0.2,0.27,0.41,0.27,0.36,0.2,0.58,0.53,0.21,...,0.33,0.00,0.00,0.00,0.38,0.00,0.43,0.50,0.0,0.00
Normalized 43,0.22,0.4,1.00,0.47,0.53,0.18,0.3,0.92,0.13,0.33,...,0.33,0.44,0.17,0.63,0.44,0.33,0.43,0.00,0.0,0.00
Normalized 44,0.28,0.5,0.18,0.06,0.27,0.36,0.3,0.08,0.67,0.08,...,0.33,0.44,0.50,0.25,0.19,0.33,0.57,0.00,0.0,0.00
Normalized 45,0.39,0.1,0.18,0.12,0.60,0.27,0.6,0.42,0.00,0.63,...,0.00,0.56,0.17,0.13,0.25,0.00,0.29,0.50,0.5,0.00
Normalized 46,0.50,0.1,0.36,0.24,0.20,0.55,0.2,0.42,0.27,0.17,...,0.00,0.67,0.50,0.13,0.25,0.00,0.57,0.50,0.5,0.00
Normalized 47,0.00,0.4,0.45,0.35,0.20,0.45,0.6,0.25,0.27,0.29,...,0.33,0.33,0.50,0.13,0.50,0.33,0.71,0.00,0.0,0.00
Normalized 48,0.22,0.5,1.00,0.71,0.13,0.27,0.2,0.33,0.47,0.38,...,0.00,0.44,0.33,0.38,0.25,0.00,0.71,0.00,0.0,0.00
Normalized 49,0.17,0.1,0.45,0.35,0.53,0.27,0.4,0.08,0.60,0.58,...,0.00,0.56,0.00,0.13,1.00,0.00,0.71,0.00,0.0,0.00
Normalized 50,0.11,0.6,0.45,0.29,0.33,0.91,0.2,0.50,0.27,0.38,...,0.00,0.33,0.17,0.50,0.44,0.67,0.86,1.00,1.0,0.00
Normalized 51,0.39,0.0,0.36,0.35,0.40,0.55,0.1,0.50,0.67,0.46,...,0.33,0.56,0.67,0.50,0.69,0.00,0.71,0.75,0.0,0.33

In [67]:

columns = list(data)
for col in columns[0:]: 
    data[col] = np.where(data[col] >= 0.5, 1, data[col])
    data[col] = np.where(data[col] < 0.5, 0, data[col])

In [68]:
data

Product_Code,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10,...,P810,P811,P812,P813,P814,P815,P816,P817,P818,P819
Normalized 0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Normalized 1,1.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Normalized 2,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Normalized 3,0.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
Normalized 4,1.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Normalized 5,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
Normalized 6,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
Normalized 7,1.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0
Normalized 8,0.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
Normalized 9,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Normalized 10,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Normalized 11,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
Normalized 12,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Normalized 13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
Normalized 14,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
Normalized 15,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Normalized 16,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
Normalized 17,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Normalized 18,0.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
Normalized 19,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
Normalized 20,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Normalized 21,0.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Normalized 22,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0
Normalized 23,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,...,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
Normalized 24,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
Normalized 25,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
Normalized 26,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
Normalized 27,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Normalized 28,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
Normalized 29,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
Normalized 30,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Normalized 31,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
Normalized 32,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
Normalized 33,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
Normalized 34,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
Normalized 35,1.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0
Normalized 36,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Normalized 37,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Normalized 38,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
Normalized 39,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
Normalized 40,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
Normalized 41,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
Normalized 42,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
Normalized 43,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
Normalized 44,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
Normalized 45,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
Normalized 46,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0
Normalized 47,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
Normalized 48,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
Normalized 49,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,...,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
Normalized 50,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0
Normalized 51,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,...,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0

In [69]:
import mlxtend

In [70]:
from mlxtend.frequent_patterns import apriori

In [76]:
b = apriori(data, min_support=0.5, use_colnames=True, low_memory=True)

In [77]:
b

     support      itemsets
0   0.538462          (P8)
1   0.500000         (P15)
2   0.557692         (P21)
3   0.615385         (P24)
4   0.538462         (P28)
..       ...           ...
85  0.500000  (P489, P180)
86  0.500000  (P180, P540)
87  0.519231  (P180, P634)
88  0.500000  (P203, P513)
89  0.538462  (P489, P634)

[90 rows x 2 columns]